### ISSUE TITLE
PyObjC 7.0 from pip: import AppKit failing

### ISSUE THREAD

**Issue by justvanrossum** [ronaldoussoren/pyobjc#337]
Could there be something off in my environment? I get this locally as well as on GitHub Actions CI, though.

```python
Python 3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import AppKit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/lib/python3.7/site-packages/AppKit/__init__.py", line 10, in <module>
    import Foundation
  File ".../venv/lib/python3.7/site-packages/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File ".../venv/lib/python3.7/site-packages/CoreFoundation/__init__.py", line 16, in <module>
    objc.pathForFramework("/System/Library/Frameworks/CoreFoundation.framework"),
  File ".../venv/lib/python3.7/site-packages/objc/_dyld.py", line 148, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File ".../venv/lib/python3.7/site-packages/objc/_dyld.py", line 142, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File ".../venv/lib/python3.7/site-packages/objc/_dyld.py", line 101, in dyld_framework
    if _dyld_shared_cache_contains_path(f):
NotImplementedError: _dyld_shared_cache_contains_path not available
>>> 
```

**Comment by justvanrossum** [comment]
This is on 10.15.7 FWIW. Python from python.org.

**Comment by AndrewHoos** [comment]
Looks like pyobjc7 is not compatible with any 10.x release of macOS only 11.0

**Comment by ronaldoussoren** [comment]
Thanks to Lawrence D'Anna for the bug fix.  There will be a 7.0.1 release soon.

**Comment by justvanrossum** [comment]
Wow that was fast, thanks!!!

**Comment by ronaldoussoren** [comment]
I'm a bit annoyed that I haven't run the test suite on 10.15 recently :-( . I'm doing that now and will push out a release when that's done.
