### ISSUE TITLE
Apple Notarize requirement break pjobjc apps

### ISSUE THREAD

**Issue by adigeo** [ronaldoussoren/pyobjc#347]
Subject to Apple requirements for notarizing apps distributed outside App Store, the setting 

ENABLE_HARDENED_RUNTIME = YES

must be used in Xcode project build settings.

As a result fo this, my pyobjc application that otherwise works fine crashes with the following traceback:

```
Traceback (most recent call last):
  File "Main.py", line 15, in <module>
    from util import memory_stick_mode
  File "/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-bjpnqrmpgwomrahhhxcxbsmhbdig/Build/Products/Debug/Blink.app/Contents/Resources/util.py", line 9, in <module>
    from AppKit import NSApp, NSRunAlertPanel
  File "/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-bjpnqrmpgwomrahhhxcxbsmhbdig/Build/Products/Debug/Blink.app/Contents/Resources/lib/AppKit/__init__.py", line 10, in <module>
    import Foundation
  File "/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-bjpnqrmpgwomrahhhxcxbsmhbdig/Build/Products/Debug/Blink.app/Contents/Resources/lib/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-bjpnqrmpgwomrahhhxcxbsmhbdig/Build/Products/Debug/Blink.app/Contents/Resources/lib/CoreFoundation/__init__.py", line 10, in <module>
    from CoreFoundation import _metadata
  File "/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-bjpnqrmpgwomrahhhxcxbsmhbdig/Build/Products/Debug/Blink.app/Contents/Resources/lib/CoreFoundation/_metadata.py", line 24, in <module>
    "CFXMLEntityInfo": objc.createStructType(
  File "/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-bjpnqrmpgwomrahhhxcxbsmhbdig/Build/Products/Debug/Blink.app/Contents/Resources/lib/objc/_bridgesupport.py", line 850, in createStructType
    result = _orig_createStructType(name, typestr, fieldnames, doc, pack)
MemoryError
2021-02-13 14:00:26.699474-0300 Blink[58226:8898211] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '/Users/adigeo/work/blink3/main.m:41 main() PyRun_SimpleFile failed with file '/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-bjpnqrmpgwomrahhhxcxbsmhbdig/Build/Products/Debug/Blink.app/Contents/Resources/Main.py'.  See console for errors.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4d298a7d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7798fa17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4d2988af +[NSException raise:format:] + 201
	3   Blink                               0x0000000100001947 main + 1463
	4   libdyld.dylib                       0x00007fff7915d3d5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff792982c6 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x0000000100a6e80d libsystem_pthread.dylib`pthread_kill + 284
    frame #2: 0x00007fff792026a6 libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff763de641 libc++abi.dylib`abort_message + 231
    frame #4: 0x00007fff763de7df libc++abi.dylib`default_terminate_handler() + 267
    frame #5: 0x00007fff77991ee3 libobjc.A.dylib`_objc_terminate() + 97
    frame #6: 0x00007fff763ea19e libc++abi.dylib`std::__terminate(void (*)()) + 8
    frame #7: 0x00007fff763e9f86 libc++abi.dylib`__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
    frame #8: 0x00007fff763dcf99 libc++abi.dylib`__cxa_throw + 113
    frame #9: 0x00007fff7798fb51 libobjc.A.dylib`objc_exception_throw + 362
    frame #10: 0x00007fff4d2988af CoreFoundation`+[NSException raise:format:] + 201
  * frame #11: 0x0000000100001947 Blink`main(argc=3, argv=0x00007ffeefbff498) at main.m:40:9
    frame #12: 0x00007fff7915d3d5 libdyld.dylib`start + 1
    frame #13: 0x00007fff7915d3d5 libdyld.dylib`start + 1
(lldb) 
```

I run the latest Python installed from https://www.python.org/downloads/release/python-391/

and pyobjc installed using pip3 install pyobjc

**Comment by adigeo** [comment]
The same result is obtained by first building the app, which runs fine and subsequently notarizing the app with Apple.

The resulted notarized app crashes with:

```
adigeo@ag13pro-57:~/work/blink3/Distribution/Notary/Blink 2021-02-17 12-29-19/Blink - Notarized/Blink.app/Contents/MacOS$ls
Blink
adigeo@ag13pro-57:~/work/blink3/Distribution/Notary/Blink 2021-02-17 12-29-19/Blink - Notarized/Blink.app/Contents/MacOS$./Blink 
Start imports
Traceback (most recent call last):
  File "Main.py", line 16, in <module>
    import Foundation
  File "/Users/adigeo/work/blink3/Distribution/Notary/Blink 2021-02-17 12-29-19/Blink - Notarized/Blink.app/Contents/Resources/lib/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/Users/adigeo/work/blink3/Distribution/Notary/Blink 2021-02-17 12-29-19/Blink - Notarized/Blink.app/Contents/Resources/lib/CoreFoundation/__init__.py", line 10, in <module>
    from CoreFoundation import _metadata
  File "/Users/adigeo/work/blink3/Distribution/Notary/Blink 2021-02-17 12-29-19/Blink - Notarized/Blink.app/Contents/Resources/lib/CoreFoundation/_metadata.py", line 24, in <module>
    "CFXMLEntityInfo": objc.createStructType(
  File "/Users/adigeo/work/blink3/Distribution/Notary/Blink 2021-02-17 12-29-19/Blink - Notarized/Blink.app/Contents/Resources/lib/objc/_bridgesupport.py", line 850, in createStructType
    result = _orig_createStructType(name, typestr, fieldnames, doc, pack)
MemoryError
2021-02-17 12:50:18.667 Blink[39227:2299020] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '/Users/adigeo/work/blink3/main.m:41 main() PyRun_SimpleFile failed with file '/Users/adigeo/work/blink3/Distribution/Notary/Blink 2021-02-17 12-29-19/Blink - Notarized/Blink.app/Contents/Resources/Main.py'.  See console for errors.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2eb8ca7d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff59283a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2eb8c8af +[NSException raise:format:] + 201
	3   Blink                               0x000000010d2ff73a Blink + 5946
	4   libdyld.dylib                       0x00007fff5aa513d5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6 (core dumped)
```

**Comment by adigeo** [comment]
We have submitted a support request with Apple for this case as well

**Comment by adigeo** [comment]
Hello,

I have received an incurraging answer from apple Apple. 

===

I’m responding to your report of problems running a PyObjC app on modern versions of macOS.  Before we start, I want to be clear about DTS’s terms of service.  DTS’s role here at Apple is to support the APIs in our platform SDKs, Apple tools, some Apple services (like notarisation), and accessory development.  We do not support third-party tools or libraries.

In the case of an open source tool like PyObjC, DTS is happy to assist you on the assumption that you ‘own’ all of the tool’s code.  That is, we expect you to dig through the tool’s code to find the point where it interacts with Apple’s APIs, at which point we can explain why the Apple API is behaving the way it is and how to adjust the tool’s code to account for that.

If you’re prepared to take on that responsibility then let me know and we can proceed with this tech support incident (TSI).  If not, DTS is unable to help you and we recommend that you engage with the support channel for the third-party tool you’re using.  In that case I’ll cancel this TSI and return the asset that it consumed to your account so that you can use it for some other technical question in the future.

Oh, there’s one other possibility here: If the folks working on this tool want to discuss this issue with DTS but don’t have their own TSI assets, you could invite them to join you on this TSI.

Apple support

They are willing to help dig into this but as they have suggested the owner of the tools used must participate too. 

As Ronand is the owner of this project I would like to ask if he is interested in helping with this.

**Comment by ronaldoussoren** [comment]
Too be honest I don't use Notarization myself yet, I'm at this point still getting away with unsigned applications.  Looking into this is on my todo list however.

Is this something you can reproduce with a small shareable project (for example one based on one of the examples in pyobjc-framework-Cocoa)? 

It might be necessary to include additional entitlements, AFAIK the application signatures on the Python.org framework add a number of entitlements that are needed for common use of Python.

**Comment by adigeo** [comment]
How to reproduce the problem:

git clone https://github.com/AGProjects/blink-cocoa
cd blink-cocoa
wget http://download.ag-projects.com/Blink/MacOSX/deps/D.tgz
tar zxvf D.tgz
open Blink.xcodeproj

Hit build in Xcode and the software will start, GUI will display. If we are so far hit stop.

Now, to reproduce the problem.

Set Target Blink -> Build Settings -> Enable Hardened Runtime to YES

Build again: The result is:

```
Traceback (most recent call last):
  File "Main.py", line 17, in <module>
    import Foundation
  File "/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-edonjexqwojzeqdywhfcswwawyjm/Build/Products/Debug/Blink.app/Contents/Resources/lib/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-edonjexqwojzeqdywhfcswwawyjm/Build/Products/Debug/Blink.app/Contents/Resources/lib/CoreFoundation/__init__.py", line 10, in <module>
    from CoreFoundation import _metadata
  File "/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-edonjexqwojzeqdywhfcswwawyjm/Build/Products/Debug/Blink.app/Contents/Resources/lib/CoreFoundation/_metadata.py", line 24, in <module>
    "CFXMLEntityInfo": objc.createStructType(
  File "/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-edonjexqwojzeqdywhfcswwawyjm/Build/Products/Debug/Blink.app/Contents/Resources/lib/objc/_bridgesupport.py", line 850, in createStructType
    result = _orig_createStructType(name, typestr, fieldnames, doc, pack)
MemoryError
2021-02-23 12:00:09.608672-0300 Blink[70471:3769240] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '/Users/adigeo/work/blink-cocoa/main.m:41 main() Running Python file '/Users/adigeo/Library/Developer/Xcode/DerivedData/Blink-edonjexqwojzeqdywhfcswwawyjm/Build/Products/Debug/Blink.app/Contents/Resources/Main.py failed''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff50c4ca7d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7b343a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff50c4c8af +[NSException raise:format:] + 201
	3   Blink                               0x0000000100001967 main + 1463
	4   libdyld.dylib                       0x00007fff7cb113d5 start + 1
	5   ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by ronaldoussoren** [comment]
As a quick test: Does enabling "Allow execution of JIT-compiled code" help?

**Comment by adigeo** [comment]
Where can I find this option?

**Comment by ronaldoussoren** [comment]
It is the first option for "Hardened Runtime" on the "Signing & Capabilities" tab.

I haven't tested this myself yet. I've been busy at work and spent time away from the computer during the evening.  My first attempt at building the app failed, likely due to a difference between your system and mine.   I should have some time to look into this over the weekend.

**Comment by ronaldoussoren** [comment]
Another option to try is the "Allowed Unsigned Excutable Memory" one just below this option, although that shouldn't be necessary.

PyObjC uses limited dynamic code creation to call into C from Python (and back again) using the libffi library.  I use MAP_JIT to create the memory segments for that. 

BTW. When using the system copy of libffi (default in PyObjC 7), and targeting macOS 10.15 or later the code won't use MAP_JIT but uses a libffi function to create these memory segments. From what I've heard that implementation should be fine to use without the additional entitlement.

**Comment by adigeo** [comment]
I tried by enabling Allowed Unsigned Excutable Memory and it works!

**Comment by ronaldoussoren** [comment]
Great. 

I'll add some documentation about this on the website.
