### ISSUE TITLE
With Python 3.9.4 on macOS 11.2.3 and pyobjc 7.1, I get "AttributeError: module 'Foundation' has no attribute 'NSPoint'"

### ISSUE THREAD

**Issue by twardoch** [ronaldoussoren/pyobjc#353]
With Python 3.9.4 on macOS 11.2.3 and pyobjc 7.1, I get a traceback on `from Quartz.CoreGraphics import _metadata` with `AttributeError: module 'Foundation' has no attribute 'NSPoint'`: 

```
>>> from Quartz import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adam/Library/Python/3.9/lib/python/site-packages/Quartz/__init__.py", line 110, in <module>
    _load()
  File "/Users/adam/Library/Python/3.9/lib/python/site-packages/Quartz/__init__.py", line 28, in _load
    from Quartz import CoreGraphics as m
  File "/Users/adam/Library/Python/3.9/lib/python/site-packages/Quartz/CoreGraphics/__init__.py", line 12, in <module>
    from Quartz.CoreGraphics import _metadata
  File "/Users/adam/Library/Python/3.9/lib/python/site-packages/Quartz/CoreGraphics/_metadata.py", line 16, in <module>
    misc.update({'CGFunctionCallbacks': objc.createStructType('CGFunctionCallbacks', b'{CGFunctionCallbacks=I^?^?}', []), 'CGDeviceByteColor': objc.createStructType('CGDeviceByteColor', b'{CGDeviceByteColor=CCC}', ['red', 'green', 'blue']), 'CGPoint': objc.createStructAlias('CGPoint', b'{CGPoint=dd}', objc._resolve_name('Foundation.NSPoint')), 'CGDataProviderCallbacks': objc.createStructType('CGDataProviderCallbacks', b'{CGDataProviderCallbacks=^?^?^?^?}', []), 'CGDataProviderSequentialCallbacks': objc.createStructType('CGDataProviderSequentialCallbacks', b'{CGDataProviderSequentialCallbacks=I^?^?^?^?}', []), 'CGPatternCallbacks': objc.createStructType('CGPatternCallbacks', b'{CGPatternCallbacks=I^?^?}', []), 'CGSize': objc.createStructAlias('CGSize', b'{CGSize=dd}', objc._resolve_name('Foundation.NSSize')), 'CGDeviceColor': objc.createStructType('CGDeviceColor', b'{CGDeviceColor=fff}', ['red', 'green', 'blue']), 'CGDataProviderDirectAccessCallbacks': objc.createStructType('CGDataProviderDirectAccessCallbacks', b'{CGDataProviderDirectAccessCallbacks=^?^?^?^?}', []), 'CGAffineTransform': objc.createStructType('CGAffineTransform', b'{CGAffineTransform=dddddd}', ['a', 'b', 'c', 'd', 'tx', 'ty']), 'CGDataConsumerCallbacks': objc.createStructType('CGDataConsumerCallbacks', b'{CGDataConsumerCallbacks=^?^?}', []), 'CGVector': objc.createStructType('CGVector', b'{CGVector=dd}', ['dx', 'dy']), 'CGPathElement': objc.createStructType('CGPathElement', b'{CGPathElement=i^{CGPoint=dd}}', ['type', 'points']), 'CGScreenUpdateMoveDelta': objc.createStructType('CGScreenUpdateMoveDelta', b'{CGScreenUpdateMoveDelta=ii}', ['dX', 'dY']), 'CGEventTapInformation': objc.createStructType('CGEventTapInformation', b'{__CGEventTapInformation=IIIQiiBfff}', ['eventTapID', 'tapPoint', 'options', 'eventsOfInterest', 'tappingProcess', 'processBeingTapped', 'enabled', 'minUsecLatency', 'avgUsecLatency', 'maxUsecLatency']), 'CGPSConverterCallbacks': objc.createStructType('CGPSConverterCallbacks', b'{CGPSConverterCallbacks=I^?^?^?^?^?^?^?}', []), 'CGRect': objc.createStructAlias('CGRect', b'{CGRect={CGPoint=dd}{CGSize=dd}}', objc._resolve_name('Foundation.NSRect'))})
  File "/Users/adam/Library/Python/3.9/lib/python/site-packages/objc/__init__.py", line 55, in _resolve_name
    return getattr(m, name)
AttributeError: module 'Foundation' has no attribute 'NSPoint'
```

**Comment by twardoch** [comment]
I uninstalled the release pyobjc:

```
python3 -m pip freeze | grep pyobjc | while read p; do python3 -m pip uninstall -y "$p"; done;
```

and installed the development branch

```
git clone --branch master --single-branch --depth 1 https://github.com/ronaldoussoren/pyobjc && python3 pyobjc/install.py
```

and the problem is now fixed. Thank you!
