### ISSUE TITLE
Symbol not found: _ffi_find_closure (Mac OS Big Sur) 

### ISSUE THREAD

**Issue by wptmdoorn** [ronaldoussoren/pyobjc#355]
Hi everyone,

First of all - thank you for this great library. I have been trying to perform some text-to-speech operations using the `pyttsx3` library which uses `PyObjC` in its backend. Unfortunately I cannot get the library to work on my new Apple M1 laptop with macOS Big Sur. I am not completely sure where to go with in relation to the error message I am getting. 

System and software specifications:
```
macOS Big Sur version 11
Python 3.8.6  
pyttsx3 3.90  
pyobjc 7.10
```

For now, I am just trying out a fairly simple code snippet which is (unfortunately) not running:

```
import pyttsx3

engine = pyttsx3.init()
engine.save_to_file("test 1 2 3", 'test.mp3')
engine.runAndWait()  
```

This returns the following error:

```
Traceback (most recent call last):
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wptmdoorn/Documents/Programmeren/Hobby/Projecten/pubmedtoaudio/pubmedtoaudio/test.py", line 3, in <module>
    engine = pyttsx3.init()
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/pyttsx3/drivers/nsss.py", line 2, in <module>
    from Foundation import *
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/CoreFoundation/__init__.py", line 9, in <module>
    import objc
  File "/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/objc/__init__.py", line 6, in <module>
    from . import _objc
ImportError: dlopen(/Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so, 2): Symbol not found: _ffi_find_closure_for_code_np
  Referenced from: /Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/wptmdoorn/miniforge3/envs/mainenv/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so
```

Analyzing this traceback it looks something related to `pyobjc` although I am not fully convinced. I have tried multiple versions of pyttsx3 and pyobjc but none of these combinations worked. Furthermore I have checked multiple solutions provided before on here, but also none of them worked (most of them were related to installing pyobjc). Would anybody have an idea what is going here?

Thanks a lot in advance. 
All the best, William

**Comment by ronaldoussoren** [comment]
That's weird, this is supposed to work fine and does so on my machine (also M1).

How was PyObjC installed? Did you use the wheels on PyPI or some other installation method?

Does upgrading to PyObjC 7.2 change anything for your?

**Comment by wptmdoorn** [comment]
I just installed a clean virtual environment with pyobjc and pyttsx3. All issues are resolved now with pyobjc >=7.2 (so also the master which is 7.2.1). I will further investigate what's caused the problem, but this is most likely on pyttsx3 side. I will close this issue for now - in case I have interesting findings I will update you on a later notice. 

My apologies for disturbing your time!

**Comment by leofang** [comment]
Hi @ronaldoussoren I also encountered this error when installing PyObjC via pip into a Conda environment locally. The reproducible steps are as follows:
```
conda create -n my_env -c conda-forge python=3.8 numpy cython
conda activate my_env
pip install pyobjc
python -c "import objc"
```
Output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/leofang/miniforge3/envs/metal_dev/lib/python3.8/site-packages/objc/__init__.py", line 6, in <module>
    from . import _objc
ImportError: dlopen(/Users/leofang/miniforge3/envs/metal_dev/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so, 2): Symbol not found: _ffi_find_closure_for_code_np
  Referenced from: /Users/leofang/miniforge3/envs/metal_dev/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/leofang/miniforge3/envs/metal_dev/lib/python3.8/site-packages/objc/_objc.cpython-38-darwin.so
```

On the Conda-Forge side, there's an attempt to support M1: https://github.com/conda-forge/pyobjc-core-feedstock/pull/34 But, CF has no access to any M1-based CI to verify if the build is correct, plus the PY38 build is currently failing, so even if it builds I suspect we'd still run into the same issue since CF, like MacPorts and Homebrew, also uses its own `libffi`. I think it'd be nice if #317 could get in asap...Thanks!

**Comment by leofang** [comment]
Hmmm interesting the very same steps work if I change `python=3.8` to `python=3.9`. This is consistent with our observation in the Conda-Forge PR. @ronaldoussoren Any insight? 😅

**Comment by ronaldoussoren** [comment]
PyObjC assumes it is build using the system version of libffi, I no longer support a non-system version of libffi. 

Note that Python 3.9 (and later) contain a number of patches that are required for good support of Big Sur and M1, in particular in the ctypes library. Those patches have not been back ported to 3.8, and won't be.

**Comment by leofang** [comment]
Thank you @ronaldoussoren. I have better clues now. Given the tests I've done I think it is fine to build pyobjc in a Conda environment; it does not pick up libffi provided by conda-forge.
