### ISSUE TITLE
importing LaunchServices in python2 

### ISSUE THREAD

**Issue by schriftgestalt** [ronaldoussoren/pyobjc#461]
I have a legacy app that still needs python 2. I could barely keep it working in macOS 12.3 (after apple removed python2.7). 

When installing python2.7 and pyobjc, most things work now except this:
```
>>> import LaunchServices
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/LaunchServices/__init__.py", line 9, in <module>
    import CoreServices
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/CoreServices/__init__.py", line 15, in <module>
    from CoreServices import LaunchServices
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/CoreServices/LaunchServices/__init__.py", line 17, in <module>
    objc.pathForFramework('/System/Library/Frameworks/CoreServices.framework/CoreServices'),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/objc/_dyld.py", line 122, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/objc/_dyld.py", line 117, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/objc/_dyld.py", line 88, in dyld_framework
    raise ImportError("Framework %s could not be found" % (framework_name,))
ImportError: Framework CoreServices could not be found
```
and importing CoreServices doesn't work either:
```
>>> import CoreServices
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/CoreServices/__init__.py", line 15, in <module>
    from CoreServices import LaunchServices
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/CoreServices/LaunchServices/__init__.py", line 17, in <module>
    objc.pathForFramework('/System/Library/Frameworks/CoreServices.framework/CoreServices'),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/objc/_dyld.py", line 122, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/objc/_dyld.py", line 117, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/objc/_dyld.py", line 88, in dyld_framework
    raise ImportError("Framework %s could not be found" % (framework_name,))
ImportError: Framework CoreServices could not be found
```

I know hat is a very old version, is there anything that can be done?

(the pyPI index is a bit confusing about the python versions. PyobjC 6 and 7 list python2.7 in the programming language section)

**Comment by schriftgestalt** [comment]
I found another issue. When I do `from Foundation import *` inside my app, I get this:
```
Traceback (most recent call last):
  File "<macro>", line 1, in <module>
  File "_lazyimport.py", line 143, in __getattr__
    raise AttributeError(name)
AttributeError: Swift.__RawSetStorage
```

As far as I can see I’m not doing anything with Swift in the app.

**Comment by ronaldoussoren** [comment]
The AttributeError is caused by ``objc._lazyimport.ObjCLazyModule.__calc_all``, and in particular the code that handles the result of ``objc.getClassList``. This was changed to ignore class names with a dot in them, like so:

```python
        # Add all class names, ignoring names with a dot because
        # those are not valid attribute names (and in general are private)
        all_names.update(
            cls.__name__ for cls in getClassList() if "." not in cls.__name__
        )
```

BTW. In general is better to not use "from Foundation import *", that is noticeably slow due to the large amount of symbols in the Foundation and CoreFoundation frameworks, most of which you won't use.  That's why PyObjC uses a lazy importer that for the most part only resolves names that are actually used.

Using a pattern like this avoids a star-import without having a huge blob of imports at the top of the module:

```python
import Foundation as F

...

F.NSArray.arrayWithArray_([1,2,3])
```

**Comment by schriftgestalt** [comment]
I know that it is slow and I try to avoid it as much as possible. But it is convenient for users that are just starting with scripting. 
Is there any change that you back-port this to the 2.7 pyobjc?

**Comment by ronaldoussoren** [comment]
Sorry, but no.  I barely have the bandwidth to maintain the current versions of my projects and no longer use Python 2.7 myself.

**Comment by schriftgestalt** [comment]
Would you accept a pull request?
