### ISSUE TITLE
Cannot update to version 8.5 with pip for Python3.10

### ISSUE THREAD

**Issue by eamarten** [ronaldoussoren/pyobjc#467]
$ pip3 install -U pyobjc    
Requirement already satisfied: pyobjc in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (8.4.1)
Collecting pyobjc
  Downloading pyobjc-8.5-py3-none-any.whl (3.8 kB)
Collecting pyobjc-framework-CloudKit==8.5
  Downloading pyobjc-framework-CloudKit-8.5.tar.gz (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.2/69.2 KB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'zip_safe'
        warnings.warn(msg)
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'python_requires'
        warnings.warn(msg)
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'install_requires'
        warnings.warn(msg)
      running egg_info
      creating /private/var/folders/22/1v351fd93qjf7j2gg8b7ztbh0000gn/T/pip-pip-egg-info-lfimel7j/pyobjc_framework_CloudKit.egg-info
      writing manifest file '/private/var/folders/22/1v351fd93qjf7j2gg8b7ztbh0000gn/T/pip-pip-egg-info-lfimel7j/pyobjc_framework_CloudKit.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/22/1v351fd93qjf7j2gg8b7ztbh0000gn/T/pip-install-kafvrk63/pyobjc-framework-cloudkit_b9fa1b9a3b9a46eb9c714082a9001d19/setup.py", line 14, in <module>
          setup(
        File "/private/var/folders/22/1v351fd93qjf7j2gg8b7ztbh0000gn/T/pip-install-kafvrk63/pyobjc-framework-cloudkit_b9fa1b9a3b9a46eb9c714082a9001d19/pyobjc_setup.py", line 645, in setup
          _setup(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/private/var/folders/22/1v351fd93qjf7j2gg8b7ztbh0000gn/T/pip-install-kafvrk63/pyobjc-framework-cloudkit_b9fa1b9a3b9a46eb9c714082a9001d19/pyobjc_setup.py", line 61, in run
          egg_info.egg_info.run(self)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 308, in run
          self.find_sources()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 315, in find_sources
          mm.run()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
          sdist.add_defaults(self)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 226, in add_defaults
          self._add_defaults_python()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/sdist.py", line 111, in _add_defaults_python
          build_py = self.get_finalized_command('build_py')
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 299, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/build_py.py", line 31, in finalize_options
          self.exclude_package_data = self.distribution.exclude_package_data or {}
      AttributeError: 'Distribution' object has no attribute 'exclude_package_data'. Did you mean: 'exclude_package'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ronaldoussoren** [comment]
I have two questions:

1. What version of setuptools is installed?
2. Could you try to install again, I've uploaded some missing wheels which should make it possible to install without hitting this error path.

**Comment by eamarten** [comment]
It is version 62.1.0.
Tried to install again, this time successfully, many thanks for your support!

**Comment by ronaldoussoren** [comment]
Great!
