### ISSUE TITLE
Problem with webView_runJavaScriptConfirmPanelWithMessage_initiatedByFrame_completionHandler metadata

### ISSUE THREAD

**Issue by r0x0r** [ronaldoussoren/pyobjc#512]
Metadata for webView_runJavaScriptConfirmPanelWithMessage_initiatedByFrame_completionHandler seems to be incorrect. Calling completion handler with a boolean value results in the following exception
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxxx/testvenv/lib/python3.9/site-packages/objc/_convenience.py", line 158, in __call__
    return _block_call(self, self.__block_signature__, args, kwds)
TypeError: Need 1 arguments, got 1
```

Example code:
```
class BrowserDelegate(AppKit.NSObject):
        def webView_runJavaScriptConfirmPanelWithMessage_initiatedByFrame_completionHandler_(self, webview, message, frame, handler):
            handler(Foundation.YES)
```

Metadata description for this selector (from WebKit/_metadata.py) is 
```
r(
        b"NSObject",
        b"webView:runJavaScriptAlertPanelWithMessage:initiatedByFrame:completionHandler:",
        {
            "required": False,
            "retval": {"type": b"v"},
            "arguments": {
                2: {"type": b"@"},
                3: {"type": b"@"},
                4: {"type": b"@"},
                5: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    },
                    "type": "@?",
                },
            },
        },
    )
```

If I read this code correctly it assumes that the argument to the handler is void, while it should be boolean.

**Platform information**

* Python version : 3.9
* How was python installed (python.org, anaconda, homebrew, ...): pip / virtualenv
* macOS version: 12.6
* pyobjc version: 9.0

**Comment by ronaldoussoren** [comment]
Thanks for the report. I've fixed the issue and the repository. Current plan is to push out a bug fix release during the weekend.
