### ISSUE TITLE
Failure on pyobjc libraries when installing cmus-osx

### ISSUE THREAD

**Issue by thinkbulecount2** [ronaldoussoren/pyobjc#516]
**Describe the bug**
I've been trying to run `pip3 install cmus-osx` but the install fails each time on any pyobjc install. I've tried to manually install pyobjc via cloning this git repo and/or `pip install pyobjc` to no avail.

This is what I keep getting:

```
Collecting pyobjc-framework-libdispatch==6.2.2
  Using cached pyobjc-framework-libdispatch-6.2.2.tar.gz (26 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/w1/s34ty6yd2q19p_w8v2cph44m0000gp/T/pip-install-3lpm1x7p/pyobjc-framework-libdispatch_396179b86b3d4704b9e40813ad51b415/setup.py", line 23, in <module>
          py_limited_api=True,
        File "/private/var/folders/w1/s34ty6yd2q19p_w8v2cph44m0000gp/T/pip-install-3lpm1x7p/pyobjc-framework-libdispatch_396179b86b3d4704b9e40813ad51b415/pyobjc_setup.py", line 436, in Extension
          % (tuple(map(int, os.path.basename(data)[6:-4].split("."))))
      ValueError: invalid literal for int() with base 10: ''
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
````

**Platform information**

* Python version
3.7.13 (I use pyenv)

* How was python installed (python.org, anaconda, homebrew, ...)
Homebrew

* macOS version
macOS Ventura

**To Reproduce**
`pip3 install cmus-osx`

**Expected behavior**
Successful install of cmus-osx.

**Comment by ronaldoussoren** [comment]
cmus-osx depends on PyObjC 6.x, which is no longer supported. The installation error you ran into is fixed in a later version of PyObjC
