### ISSUE TITLE
How can I fix `FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/sw_vers'` error?

### ISSUE THREAD

**Issue by avatar-lavventura** [ronaldoussoren/pyobjc#520]
When try to install `pyobjc` using ` pip install pyobjc-framework-Cocoa` I am getting following error, how can I fix this?:
I believe if this package is tried to be installed in ubuntu-linux machine it does not handle this.

```
$ pip install pyobjc-framework-Cocoa
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-sf7u4bxm/pyobjc-framework-cocoa_30d04f6b8ac141838b3c57e17ef36afe/setup.py", line 22, in <module>
          Extension(
        File "/tmp/pip-install-sf7u4bxm/pyobjc-framework-cocoa_30d04f6b8ac141838b3c57e17ef36afe/pyobjc_setup.py", line 462, in Extension
          os_level = get_os_level()
        File "/tmp/pip-install-sf7u4bxm/pyobjc-framework-cocoa_30d04f6b8ac141838b3c57e17ef36afe/pyobjc_setup.py", line 231, in get_os_level
          subprocess.check_output(["/usr/bin/sw_vers", "-productVersion"])
        File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.8/subprocess.py", line 493, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/sw_vers'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ronaldoussoren** [comment]
What platform are you trying to install PyObjC on?  PyObjC is a macOS specific package and cannot be used on other platforms, such as Linux.

**Comment by avatar-lavventura** [comment]
I was trying to install it on Linux, it was located on my requirements.txt. As I understand I have to do requirements.txt file for macOS and Linux separately, where Linux won't contain the PyObjC package.

**Comment by ronaldoussoren** [comment]
You don't have to have two files, requirements.txt can contain environment markers and using that you can select pyobjc only on macOS:

```
pyobjc-framework-Cocoa ; sys_platform == "darwin"
```

The platform name is "darwin" because that's how the kernel on macOS self-identifies.
