### ISSUE TITLE
bridgesupport imports deprecated pkg_resources

### ISSUE THREAD

**Issue by jaraco** [ronaldoussoren/pyobjc#537]
The Setuptools project is deprecating pkg_resources.

Although _bridgesupport is itself deprecated, it unconditionally imports pkg_resources, triggering a DeprecationWarning.

Probably the deprecation warning can be suppressed or the import can be bound late to avoid the DeprecationWarning on import, or possibly it could be ported to importlib.resources.

**Comment by jaraco** [comment]
I can replicate the issue thus:

```
 ~ $ env PYTHONWARNINGS=error pip-run pyobjc 'setuptools>=67.5' -- -c "import Foundation"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-nlgmga0n/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-nlgmga0n/CoreFoundation/__init__.py", line 9, in <module>
    import objc
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-nlgmga0n/objc/__init__.py", line 40, in <module>
    from ._bridgesupport import *  # noqa: F401, F403, E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-nlgmga0n/objc/_bridgesupport.py", line 15, in <module>
    import pkg_resources
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-nlgmga0n/pkg_resources/__init__.py", line 121, in <module>
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
DeprecationWarning: pkg_resources is deprecated as an API
```
