### ISSUE TITLE
AttributeError: dlsym(0x3a0604b58, objc_msgSendSuper_stret): symbol not found

### ISSUE THREAD

**Issue by monkey410** [ronaldoussoren/pyobjc#553]
**Platform information**

* Python 3.8
* python installed (homebrew)
* macOS version 13.0，M1

**To Reproduce**
import pyautogui

**Actual behavior**
Traceback (most recent call last):
  File "/Users/jxtech-liu/Desktop/demo/Code/demo.py", line 3, in <module>
    import pyautogui
  File "/opt/homebrew/lib/python3.8/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/opt/homebrew/lib/python3.8/site-packages/mouseinfo/__init__.py", line 100, in <module>
    from rubicon.objc import ObjCClass, CGPoint
  File "/opt/homebrew/lib/python3.8/site-packages/rubicon/objc/__init__.py", line 33, in <module>
    from . import api, collections, runtime, types
  File "/opt/homebrew/lib/python3.8/site-packages/rubicon/objc/api.py", line 28, in <module>
    from .runtime import (
  File "/opt/homebrew/lib/python3.8/site-packages/rubicon/objc/runtime.py", line 460, in <module>
    libobjc.objc_msgSendSuper_stret.restype = None
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
**AttributeError: dlsym(0x3a0604b58, objc_msgSendSuper_stret): symbol not found**

**Comment by monkey410** [comment]
Referencing similar questions does not solve the problem：https://github.com/moses-palmer/pynput/issues/420

**Comment by crossxx-labs** [comment]
It's a pyobjc issue. I switched to python3.8 and re-installed pyobjc from git repo,  then the error disappeared. [Details here](https://github.com/asweigart/pyautogui/issues/772#issuecomment-1931241870)

**Comment by ronaldoussoren** [comment]
- Which version of Python?
- Which version of PyObjC?
- Which version of macOS?
- How did you install Python?
- How did you install PyObjC?

Also, the issue you link to has a traceback that doesn't involve PyObjC. PyObjC doesn't use ctypes to access Objective-C runtime APIs.
